### PR TITLE
Add w_val option

### PR DESCRIPTION
**Pull request by apeace**
Needed to use this, so figured I would share. Thanks for the great lib!

### CODE REVIEW

**Comment by DTrejo** [comment]
Hey apeace, you can see that I've written docs in the other open pull request. if you'd like to add a paragraph or two and maybe an example of how to use this, it would be much appreciated, so that they can be added to the docs as well.

Thank you,
D

**Comment by apeace** [comment]
@DTrejo I sure will! Your docs look great so far

**Comment by DTrejo** [comment]
Merged mine, so if you'd like to add a section for this, you're clear to do so.

**Comment by apeace** [comment]
Awesome, that makes it easier. Will add something soon

**Comment by DTrejo** [comment]
Thank you and apologies for the slow merging!

**Comment by apeace** [comment]
Oh snap, forgot about this and never added doc! My bad

**Comment by DTrejo** [comment]
No worries, all I needed to do was copy over the comment you added to.

**Pull request closed without merging**
